# Generated by Django 5.1.4 on 2025-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.IntegerField()),
                ('Foodname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Userid', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Firstname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.IntegerField()),
                ('Foodname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Userid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foodtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foodname', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('Quantity', models.IntegerField()),
                ('Unitprice', models.IntegerField()),
                ('Brand', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('People', models.IntegerField()),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
