# Generated by Django 5.1.4 on 2025-01-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtable',
            name='Date',
        ),
    ]
