# Generated by Django 5.1.5 on 2025-02-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="basicdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Age", models.IntegerField()),
                ("Phone", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Gender", models.CharField(max_length=100)),
                ("Date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="educationdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("School", models.CharField(max_length=100)),
                ("Course", models.CharField(max_length=100)),
                ("Degree", models.CharField(max_length=100)),
                ("Resource", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="employedata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Employeid", models.IntegerField()),
                ("Company", models.CharField(max_length=100)),
                ("Field", models.CharField(max_length=100)),
                ("Experience", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="filedata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Marksheet", models.FileField(upload_to="")),
                ("Degree", models.FileField(upload_to="")),
                ("Passport", models.FileField(upload_to="")),
                ("Medical", models.FileField(upload_to="")),
                ("Work", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="financialdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Bank", models.CharField(max_length=100)),
                ("Account", models.IntegerField()),
                ("Ifsc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="medicaldata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Age", models.IntegerField()),
                ("Height", models.CharField(max_length=100)),
                ("Weight", models.IntegerField()),
                ("Health", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Gmail", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
    ]
